import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/router';
import { UserShell } from '../../components/user-shell';
import { Card, EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge, Stack } from '../../components/foundation';
import { createApiClient } from '../../lib/api-client';
import { readSession } from '../../lib/session';

export default function ProviderDetail() {
  const router = useRouter(); const api = useMemo(() => createApiClient({ getSession: readSession }), []);
  const [item, setItem] = useState(null); const [eligibility, setEligibility] = useState(null); const [code, setCode] = useState(null); const [message, setMessage] = useState('در حال بارگذاری…'); const [busy, setBusy] = useState(false); const [remaining, setRemaining] = useState(null);
  useEffect(() => { if (!router.isReady) return; api.get(`/providers/${router.query.id}`).then((row) => { setItem(row); setMessage(''); }).catch((e) => setMessage(e.status === 404 ? 'این پزشک پیدا نشد.' : e.message)); }, [api, router.isReady, router.query.id]);
  useEffect(() => { if (!code?.tokenExpiresAt) return undefined; const tick = () => setRemaining(Math.max(0, new Date(code.tokenExpiresAt).getTime() - Date.now())); tick(); const timer = globalThis.setInterval(tick, 1000); return () => globalThis.clearInterval(timer); }, [code]);
  async function checkEligibility() { setBusy(true); try { setEligibility(await api.get(`/providers/${router.query.id}/eligibility`)); } catch (e) { setEligibility({ error: e.message }); } finally { setBusy(false); } }
  async function initiate(benefit) { setBusy(true); try { setCode(await api.post('/redemptions', { providerId: item.id, benefitMembershipId: benefit.membershipId }, { headers: { 'idempotency-key': `web-${item.id}-${benefit.membershipId}-${Date.now()}` } })); } catch (e) { setEligibility((current) => ({ ...current, error: e.message })); } finally { setBusy(false); } }
  const time = remaining == null ? '' : `${String(Math.floor(remaining / 60000)).padStart(2, '0')}:${String(Math.floor((remaining % 60000) / 1000)).padStart(2, '0')}`;
  return <UserShell title="جزئیات پزشک"><Stack><PageHeader eyebrow="پزشک یا مرکز طرف قرارداد" title={item?.displayName || 'در حال بارگذاری'} description="واجدشرایط‌بودن از API بررسی می‌شود؛ تصمیم نهایی همیشه با سرور است." />{message && (item ? <ErrorState title={message} /> : <LoadingState label={message} />)}{item && <><Card><p>نوع: {item.type}</p><p>استان: {item.province?.name || '—'} · شهر: {item.city?.name || '—'}</p><p>نشانی: {item.address || 'ثبت نشده'}</p><p>تخصص: {item.doctorProfile?.specialty?.name || 'مرکز سلامت'}</p><button className="button" type="button" onClick={checkEligibility} disabled={busy}>بررسی واجدشرایط‌بودن من</button></Card>{eligibility?.error && <ErrorState title={eligibility.error} />}{eligibility && !eligibility.error && !eligibility.eligible && <EmptyState title="در حال حاضر واجد استفاده نیستید">عضویت فعال و مزیت سازگار برای این ارائه‌دهنده پیدا نشد.</EmptyState>}{eligibility?.benefits?.map((benefit) => <Card key={`${benefit.membershipId}-${benefit.planId}`}><div className="provider-card-head"><h2>{benefit.planName}</h2><StatusBadge tone="success">واجدشرایط</StatusBadge></div><p>تخفیف: {benefit.discountValue} {benefit.discountType === 'PERCENT' ? 'درصد' : ''}</p><button className="button" type="button" onClick={() => initiate(benefit)} disabled={busy || code}>ایجاد کد یک‌بارمصرف</button></Card>)}{code && <Card><h2>کد تأیید استفاده</h2><p className="redemption-code" aria-label="کد تأیید">{code.token}</p><p role="status" aria-live="polite">اعتبار باقی‌مانده: {remaining === 0 ? 'منقضی شده' : time}</p><p>این کد فقط همین حالا نمایش داده می‌شود. پس از refresh قابل بازیابی نیست.</p><button className="button button--ghost" type="button" onClick={() => globalThis.navigator?.clipboard?.writeText(code.token)}>کپی کد</button></Card>}</>}</Stack></UserShell>;
}
