import { useEffect, useState } from 'react';
import { UserShell } from '../../components/user-shell';
import { createApiClient } from '../../lib/api-client';
import { readSession } from '../../lib/session';

export default function Providers() {
  const [provinces, setProvinces] = useState([]); const [cities, setCities] = useState([]); const [specialties, setSpecialties] = useState([]); const [items, setItems] = useState([]); const [filters, setFilters] = useState({ provinceId: '', cityId: '', specialtyId: '' }); const [message, setMessage] = useState('در حال بارگذاری…');
  const api = createApiClient({ getSession: readSession });
  useEffect(() => { Promise.all([api.get('/locations/provinces'), api.get('/specialties')]).then(([provinceRows, specialtyRows]) => { setProvinces(provinceRows); setSpecialties(specialtyRows); }).catch((e) => setMessage(e.message)); }, []);
  useEffect(() => { const query = new globalThis.URLSearchParams(); if (filters.provinceId) query.set('provinceId', filters.provinceId); if (filters.cityId) query.set('cityId', filters.cityId); if (filters.specialtyId) query.set('specialtyId', filters.specialtyId); setMessage('در حال بارگذاری…'); api.get(`/providers${query.toString() ? `?${query}` : ''}`).then((rows) => { setItems(rows || []); setMessage(''); }).catch((e) => { setItems([]); setMessage(e.message); }); }, [filters]);
  async function provinceChange(e) { const provinceId = e.target.value; setFilters({ provinceId, cityId: '', specialtyId: filters.specialtyId }); setCities(provinceId ? await api.get(`/locations/provinces/${provinceId}/cities`) : []); }
  return <UserShell title="پزشکان و مراکز"><section className="stack"><div className="filter-grid"><label>استان<select aria-label="استان" value={filters.provinceId} onChange={provinceChange}><option value="">همه استان‌ها</option>{provinces.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>شهر<select aria-label="شهر" value={filters.cityId} onChange={(e) => setFilters({ ...filters, cityId: e.target.value })}><option value="">همه شهرها</option>{cities.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>تخصص<select aria-label="تخصص" value={filters.specialtyId} onChange={(e) => setFilters({ ...filters, specialtyId: e.target.value })}><option value="">همه تخصص‌ها</option>{specialties.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div><p role="status">{message}</p>{!message && !items.length && <p>پزشک تأییدشده‌ای پیدا نشد.</p>}<ul className="card-list">{items.map((item) => <li key={item.id}><h2><a href={`/providers/${item.id}`}>{item.displayName}</a></h2><p>{item.province?.name}، {item.city?.name}</p><p>{item.address}</p>{item.doctorProfile?.specialty?.name && <p>تخصص: {item.doctorProfile.specialty.name}</p>}</li>)}</ul></section></UserShell>;
}
