import { useEffect, useState } from 'react';
import { UserShell } from '../../components/user-shell';
import { Card, EmptyState, ErrorState, LoadingState, PageHeader, Stack, StatusBadge } from '../../components/foundation';
import { createApiClient } from '../../lib/api-client';
import { readSession } from '../../lib/session';

export default function Providers() {
  const [provinces, setProvinces] = useState([]); const [cities, setCities] = useState([]); const [specialties, setSpecialties] = useState([]); const [items, setItems] = useState([]); const [filters, setFilters] = useState({ provinceId: '', cityId: '', specialtyId: '' }); const [message, setMessage] = useState('در حال بارگذاری…'); const [error, setError] = useState(false);
  const api = createApiClient({ getSession: readSession });
  useEffect(() => { Promise.all([api.get('/locations/provinces'), api.get('/specialties')]).then(([provinceRows, specialtyRows]) => { setProvinces(provinceRows); setSpecialties(specialtyRows); }).catch(() => { setError(true); setMessage('اطلاعات فیلترها قابل دریافت نیست.'); }); }, []);
  useEffect(() => { const query = new globalThis.URLSearchParams(); if (filters.provinceId) query.set('provinceId', filters.provinceId); if (filters.cityId) query.set('cityId', filters.cityId); if (filters.specialtyId) query.set('specialtyId', filters.specialtyId); setMessage('در حال بارگذاری…'); setError(false); api.get(`/providers${query.toString() ? `?${query}` : ''}`).then((rows) => { setItems(rows || []); setMessage(''); }).catch(() => { setItems([]); setMessage('فهرست پزشکان قابل دریافت نیست.'); setError(true); }); }, [filters]);
  async function provinceChange(e) { const provinceId = e.target.value; setFilters({ provinceId, cityId: '', specialtyId: filters.specialtyId }); setCities(provinceId ? await api.get(`/locations/provinces/${provinceId}/cities`) : []); }
  return <UserShell title="پزشکان و مراکز"><Stack><PageHeader eyebrow="جست‌وجوی خدمات سلامت" title="پزشک یا مرکز طرف قرارداد پیدا کنید" description="با فیلترهای زیر، گزینه‌های تأییدشده را بر اساس موقعیت و تخصص پیدا کنید." /><Card><div className="filter-grid"><label>استان<select aria-label="استان" value={filters.provinceId} onChange={provinceChange}><option value="">همه استان‌ها</option>{provinces.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>شهر<select aria-label="شهر" value={filters.cityId} onChange={(e) => setFilters({ ...filters, cityId: e.target.value })}><option value="">همه شهرها</option>{cities.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>تخصص<select aria-label="تخصص" value={filters.specialtyId} onChange={(e) => setFilters({ ...filters, specialtyId: e.target.value })}><option value="">همه تخصص‌ها</option>{specialties.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label></div></Card>{error ? <ErrorState title={message} /> : message ? <LoadingState label={message} /> : !items.length ? <EmptyState title="پزشک تأییدشده‌ای پیدا نشد">فیلترها را تغییر دهید یا بعداً دوباره تلاش کنید.</EmptyState> : <div className="provider-grid">{items.map((item) => <Card key={item.id}><div className="provider-card-head"><h2><a href={`/providers/${item.id}`}>{item.displayName}</a></h2><StatusBadge tone="success">تأییدشده</StatusBadge></div><p className="muted-text">{item.doctorProfile?.specialty?.name || 'مرکز سلامت'} · {item.province?.name}، {item.city?.name}</p><p>{item.address}</p><a className="button button--ghost" href={`/providers/${item.id}`}>مشاهده جزئیات</a></Card>)}</div>}</Stack></UserShell>;
}
