import { useEffect, useState } from 'react';
import { UserShell } from '../../components/user-shell';
import { createApiClient } from '../../lib/api-client';
import { labelStatus } from '../../lib/presentation';
import { readSession } from '../../lib/session';

const initialForm = { displayName: '', provinceId: '', cityId: '', medicalCouncilNumber: '', specialtyId: '', address: '', phone: '', imageUrl: '' };

export default function ProviderOnboarding() {
  const [form, setForm] = useState(initialForm); const [provinces, setProvinces] = useState([]); const [cities, setCities] = useState([]); const [specialties, setSpecialties] = useState([]); const [existing, setExisting] = useState(null); const [state, setState] = useState('loading'); const [message, setMessage] = useState('در حال بارگذاری…'); const [busy, setBusy] = useState(false);
  const api = createApiClient({ getSession: readSession });
  useEffect(() => { Promise.all([api.get('/locations/provinces'), api.get('/specialties'), api.get('/users/me/providers')]).then(([provinceRows, specialtyRows, providerRows]) => { setProvinces(provinceRows || []); setSpecialties(specialtyRows || []); setExisting(providerRows || []); setState('ready'); setMessage(''); }).catch((error) => { setState('error'); setMessage(error.message); }); }, []);
  async function provinceChange(event) { const provinceId = event.target.value; setForm((current) => ({ ...current, provinceId, cityId: '' })); if (!provinceId) { setCities([]); return; } try { setCities(await api.get(`/locations/provinces/${provinceId}/cities`) || []); } catch (error) { setCities([]); setMessage(error.message); } }
  function change(name, value) { setForm((current) => ({ ...current, [name]: value })); }
  async function submit(event) { event.preventDefault(); setBusy(true); setMessage('در حال ثبت پرونده…'); try { const row = await api.post('/providers/doctor-registration', { ...form, imageUrl: form.imageUrl || null, address: form.address || '', phone: form.phone || '' }); setExisting([row]); setState('submitted'); setMessage('پرونده با موفقیت برای بررسی ثبت شد.'); } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  return <UserShell title="درخواست همکاری پزشک"><section className="stack"><p role="status" aria-live="polite">{message}</p>{state === 'loading' && <p role="status">در حال آماده‌سازی فرم…</p>}{state === 'error' && <p role="alert">اطلاعات فرم قابل دریافت نیست.</p>}{state !== 'loading' && state !== 'error' && existing?.length > 0 && <section className="card"><h2>پرونده‌های شما</h2>{existing.map((item) => <article key={item.id}><h3>{item.displayName}</h3><p>وضعیت بررسی: {labelStatus(item.status)}</p><p>استان: {item.province?.name || '—'}، شهر: {item.city?.name || '—'}</p><small>این صفحه به contract فعلی پایبند است و دلیل رد یا بارگذاری مدرک را نمایش نمی‌دهد.</small></article>)}</section>}{state === 'ready' && !existing?.length && <form className="card stack" onSubmit={submit}><h2>ثبت پرونده همکاری</h2><p>اطلاعات زیر با contract فعلی ثبت می‌شود و پس از ارسال در وضعیت «در انتظار بررسی» قرار می‌گیرد.</p><label htmlFor="provider-display-name">نام نمایشی<input id="provider-display-name" required value={form.displayName} onChange={(e) => change('displayName', e.target.value)} /></label><label htmlFor="provider-province">استان<select id="provider-province" required value={form.provinceId} onChange={provinceChange}><option value="">انتخاب استان</option>{provinces.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label htmlFor="provider-city">شهر<select id="provider-city" required value={form.cityId} onChange={(e) => change('cityId', e.target.value)}><option value="">انتخاب شهر</option>{cities.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label htmlFor="provider-council">شماره نظام پزشکی<input id="provider-council" required value={form.medicalCouncilNumber} onChange={(e) => change('medicalCouncilNumber', e.target.value)} /></label><label htmlFor="provider-specialty">تخصص<select id="provider-specialty" required value={form.specialtyId} onChange={(e) => change('specialtyId', e.target.value)}><option value="">انتخاب تخصص</option>{specialties.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label htmlFor="provider-address">نشانی<input id="provider-address" value={form.address} onChange={(e) => change('address', e.target.value)} /></label><label htmlFor="provider-phone">تلفن<input id="provider-phone" value={form.phone} onChange={(e) => change('phone', e.target.value)} /></label><label htmlFor="provider-image">نشانی تصویر (اختیاری)<input id="provider-image" type="url" value={form.imageUrl} onChange={(e) => change('imageUrl', e.target.value)} /></label><button type="submit" disabled={busy}>{busy ? 'در حال ثبت…' : 'ارسال برای بررسی'}</button></form>}{state === 'submitted' && <section className="card"><h2>درخواست ثبت شد</h2><p>وضعیت فعلی: {labelStatus(existing?.[0]?.status || 'PENDING_REVIEW')}</p><a className="button button--ghost" href="/providers/me">مشاهده وضعیت پرونده</a></section>}</section></UserShell>;
}
