import { useEffect, useState } from 'react';
import { UserShell } from '../components/user-shell';
import { createApiClient, ApiError } from '../lib/api-client';
import { readSession } from '../lib/session';
import { formatMoney, labelStatus } from '../lib/presentation';

const types = { REFERRAL_REWARD: 'پاداش معرفی', REFERRAL_REVERSAL: 'برگشت پاداش معرفی', WITHDRAWAL_RESERVATION: 'رزرو برداشت', WITHDRAWAL_RELEASE: 'آزادسازی برداشت', ADMIN_ADJUSTMENT_CREDIT: 'افزایش اعتبار', ADMIN_ADJUSTMENT_DEBIT: 'کاهش اعتبار' };
const withdrawalLabels = { PENDING: 'در انتظار بررسی', APPROVED: 'تأییدشده', PAYOUT_PENDING: 'در حال پرداخت', PAYOUT_UNKNOWN: 'در حال بررسی؛ اقدامی لازم نیست', PAID: 'پرداخت‌شده', FAILED: 'ناموفق', CANCELLED: 'لغوشده', FROZEN: 'منجمد و نیازمند بررسی' };

export default function Wallet() {
  const [data, setData] = useState(null); const [transactions, setTransactions] = useState([]); const [transactionState, setTransactionState] = useState('loading'); const [withdrawals, setWithdrawals] = useState([]); const [amount, setAmount] = useState(''); const [message, setMessage] = useState('در حال بارگذاری…'); const [busy, setBusy] = useState(false); const [confirming, setConfirming] = useState(false);
  const api = createApiClient({ getSession: readSession });
  async function load() { setTransactionState('loading'); try { const [wallet, rows, transactionRows] = await Promise.all([api.get('/users/me/wallet'), api.get('/users/me/wallet/withdrawals'), api.get('/users/me/wallet/transactions')]); setData(wallet); setTransactions(Array.isArray(transactionRows) ? transactionRows : []); setTransactionState('success'); setWithdrawals(rows || []); setMessage(''); } catch (error) { setTransactionState('error'); setMessage(error.message); } }
  useEffect(() => { load(); }, []);
  function validateAmount() { const value = Number(amount); if (!Number.isSafeInteger(value) || value <= 0) { setMessage('مبلغ برداشت باید یک عدد صحیح مثبت باشد.'); return null; } return value; }
  function prepare(event) { event.preventDefault(); if (validateAmount() !== null) { setMessage('مبلغ را بررسی کنید، سپس تأیید نهایی را بزنید.'); setConfirming(true); } }
  async function submit() { const value = validateAmount(); if (value === null) return; setBusy(true); setMessage('در حال ثبت درخواست…'); try { await api.post('/users/me/wallet/withdrawals', { amount: String(value) }); setAmount(''); setConfirming(false); await load(); setMessage('درخواست برداشت ثبت شد و در وضعیت اولیه قرار گرفت.'); } catch (error) { setMessage(error instanceof ApiError ? error.message : 'ثبت درخواست برداشت ممکن نشد.'); } finally { setBusy(false); } }
  return <UserShell title="کیف پول"><p role="status" aria-live="polite">{message}</p>{data && <div className="stack"><section className="card"><h2>موجودی</h2><p data-testid="wallet-balance">{formatMoney(data.balance, data.currency)}</p></section><section className="card"><h2>درخواست برداشت</h2><form onSubmit={prepare}><label htmlFor="withdrawal-amount">مبلغ ({data.currency})</label><input id="withdrawal-amount" inputMode="numeric" value={amount} onChange={(e) => { setAmount(e.target.value); setConfirming(false); }} placeholder="مثلاً ۱۰۰۰۰۰" aria-describedby="withdrawal-help" /><small id="withdrawal-help">مبلغ باید عدد صحیح مثبت باشد؛ اعتبارسنجی نهایی با سرور است.</small><button type="submit" disabled={busy || !amount}>ادامه</button>{confirming && <div role="group" aria-label="تأیید درخواست برداشت"><p>مبلغ درخواست: {formatMoney(Number(amount), data.currency)}</p><button type="button" onClick={submit} disabled={busy}>{busy ? 'در حال ثبت…' : 'تأیید و ثبت درخواست'}</button><button type="button" onClick={() => setConfirming(false)} disabled={busy}>بازگشت</button></div>}</form></section><section className="card" aria-labelledby="wallet-transactions-heading"><h2 id="wallet-transactions-heading">تراکنش‌های کیف پول</h2>{transactionState === 'loading' && <p role="status">در حال بارگذاری تراکنش‌ها…</p>}{transactionState === 'error' && <p role="alert">سابقه تراکنش‌ها قابل دریافت نیست.</p>}{transactionState === 'success' && !transactions.length && <p>تراکنشی ثبت نشده است.</p>}{transactionState === 'success' && transactions.length > 0 && <ul className="card-list">{transactions.map((item) => <li key={item.id}><h3>{types[item.type] || 'تراکنش کیف پول'}</h3><p>{formatMoney(item.amount, item.currency)}</p><p>نوع عملیات: {item.type || 'نامشخص'}</p>{item.reference && <p>شناسه مرجع: <bdi dir="ltr">{item.reference}</bdi></p>}<small>{item.createdAt ? new Date(item.createdAt).toLocaleString('fa-IR', { timeZone: 'Asia/Tehran' }) : '—'}</small></li>)}</ul>}</section><section><h2>درخواست‌های برداشت</h2>{!withdrawals.length ? <p>درخواستی ثبت نشده است.</p> : <ul className="card-list">{withdrawals.map((item) => { const status = item.status || 'PENDING'; return <li key={item.id}><p>{formatMoney(item.amount, data.currency)}</p><p>وضعیت: {withdrawalLabels[status] || labelStatus(status)}</p>{status === 'PAYOUT_UNKNOWN' && <p role="status">وضعیت نهایی هنوز مشخص نیست؛ درخواست مجدد یا لغو از این صفحه پیشنهاد نمی‌شود.</p>}{status === 'FROZEN' && <p role="alert">این مورد برای بررسی منجمد شده است.</p>}<small>{item.createdAt ? new Date(item.createdAt).toLocaleString('fa-IR', { timeZone: 'Asia/Tehran' }) : '—'}</small></li>; })}</ul>}</section></div>}</UserShell>;
}
