import { useEffect, useState } from 'react';
import { AdminShell } from '../../components/admin-shell';
import { labelStatus } from '../../lib/presentation';
import { createApiClient } from '../../lib/api-client';
import { readSession } from '../../lib/session';

function countRows(rows) { return Array.isArray(rows) ? rows.length : 0; }

export default function AdminReporting() {
  const [data, setData] = useState(null); const [state, setState] = useState('loading'); const [message, setMessage] = useState('در حال بارگذاری گزارش عملیاتی…');
  useEffect(() => { const api = createApiClient({ getSession: readSession }); Promise.all([api.get('/admin/dashboard/summary'), api.get('/admin/purchases'), api.get('/admin/memberships'), api.get('/admin/redemptions'), api.get('/admin/withdrawals')]).then(([summary, purchases, memberships, redemptions, withdrawals]) => { setData({ summary: summary.admin, purchases: purchases || [], memberships: memberships || [], redemptions: redemptions || [], withdrawals: withdrawals || [] }); setState('success'); setMessage(''); }).catch((error) => { setState('error'); setMessage(error.message); }); }, []);
  return <AdminShell title="گزارش عملیاتی" permission="users.read"><section className="stack"><p role="status" aria-live="polite">{message}</p>{state === 'loading' && <p role="status">در حال بارگذاری…</p>}{state === 'error' && <p role="alert">گزارش عملیاتی قابل دریافت نیست.</p>}{state === 'success' && data && <><section className="metric-grid"><article className="metric-card"><h2>کاربران</h2><p>{data.summary.users_by_status.ACTIVE || 0} فعال</p><a href="/admin/users">مشاهده کاربران</a></article><article className="metric-card"><h2>پزشکان</h2><p>{data.summary.providers_by_status.APPROVED || 0} تأییدشده</p><p>{data.summary.providers_by_status.PENDING_REVIEW || 0} در انتظار بررسی</p><a href="/admin/providers">مشاهده پزشکان</a></article><article className="metric-card"><h2>طرح‌ها</h2><p>{data.summary.plan_count} طرح</p><a href="/admin/plans">مشاهده طرح‌ها</a></article><article className="metric-card"><h2>خریدها</h2><p>{countRows(data.purchases)} رکورد read-only</p><a href="/admin/purchases">مشاهده خریدها</a></article><article className="metric-card"><h2>عضویت‌ها</h2><p>{countRows(data.memberships)} رکورد read-only</p><a href="/admin/memberships">مشاهده عضویت‌ها</a></article><article className="metric-card"><h2>Redemption</h2><p>{countRows(data.redemptions)} رکورد read-only</p><a href="/admin/redemptions">مشاهده استفاده‌ها</a></article><article className="metric-card"><h2>برداشت‌ها</h2><p>{countRows(data.withdrawals)} رکورد عملیاتی</p><a href="/admin/withdrawals">مشاهده برداشت‌ها</a></article></section><section className="card"><h2>وضعیت‌های عملیاتی</h2><ul><li>خرید در انتظار: {data.summary.purchases_by_status.PENDING_PAYMENT || 0}</li><li>برداشت در انتظار: {data.summary.withdrawals_by_status.PENDING || 0}</li><li>Provider در انتظار بررسی: {data.summary.providers_by_status.PENDING_REVIEW || 0}</li></ul></section><section className="card"><h2>مرز داده</h2><p>برای Eligibility و Wallet در API فعلی aggregate عملیاتی Admin وجود ندارد؛ metric ساختگی یا محاسبه مالی از داده خام در این صفحه انجام نمی‌شود.</p><a href="/admin/providers">Eligibility از مسیر Provider بررسی می‌شود</a> · <a href="/admin/withdrawals">Wallet/Withdrawal از مسیر عملیات برداشت بررسی می‌شود</a></section><section className="card"><h2>تعریف گزارش</h2><p>این صفحه فقط snapshot read-only از contractهای موجود است؛ بازه تاریخی، export و تبدیل ارز در این Wave اضافه نشده‌اند.</p><small>وضعیت نمونه: {labelStatus(data.summary.purchases_by_status.PENDING_PAYMENT ? 'PENDING' : 'ACTIVE')}</small></section></>}</section></AdminShell>;
}
