import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs';
const root = new URL('..', import.meta.url); const read = (file) => fs.readFileSync(new URL(file, root), 'utf8');
test('B7 admin route surface is permission-based and uses real contracts', () => { const shell = read('components/admin-shell.jsx'); assert.match(shell, /can\(session, permission\)/); assert.match(read('pages/admin/users.jsx'), /admin\/users/); assert.match(read('pages/admin/providers.jsx'), /admin\/providers/); assert.match(read('pages/admin/commissions.jsx'), /admin\/commissions/); assert.match(read('pages/admin/settings.jsx'), /admin\/commercial-settings/); });
test('B7 admin UI does not invent role/report capability', () => { const page = read('pages/admin/index.jsx'); assert.match(page, /metric ساختگی/); assert.doesNotMatch(page, /roles|permissions|reports/i); });
test('support surface uses its own read-only allowlisted API contracts and shared RTL shell', () => {
  const page = read('pages/support/index.jsx'); const shell = read('components/support-shell.jsx'); const session = read('lib/session.js'); const api = read('../api/src/main.mjs');
  for (const endpoint of ['/support/summary', '/support/users', '/support/providers', '/support/purchases', '/support/memberships', '/support/redemptions', '/support/refund-cases']) assert.ok(page.includes(endpoint), endpoint);
  assert.match(shell, /support\.dashboard\.read/); assert.match(shell, /AuthenticatedShell/); assert.match(session, /permission\.startsWith\('support\.'\)/);
  assert.match(api, /if \(supportOnly && !canSupport\(permission\)\) throw new Error\('FORBIDDEN'\)/);
  assert.doesNotMatch(page, /api\.(post|patch|put|delete)\s*\(/i);
  assert.doesNotMatch(page, /'phone'|'nationalId'|'amountSnapshot'|'customerUserId'|'doctorNationalId'/i);
  assert.match(page, /entries\.length \? <ul>/);
  assert.match(page, /support-summary-empty/);
  assert.match(page, /اطلاعاتی ثبت نشده است/);
  assert.match(read('styles.css'), /\.support-summary-empty[^{]*\{[^}]*color: var\(--muted\)/);
  assert.match(read('styles.css'), /\.support-summary \{ gap: 1rem; \}/);
  assert.match(read('components/auth-form.jsx'), /supportOnly \? '\/support' : '\/dashboard'/);
});
test('Wave 41 evidence harness requires ephemeral credentials and uses the real login flow', () => {
  const script = read('e2e/wave41-support-evidence.mjs');
  const runner = read('e2e/wave41-support-one-shot.mjs');
  assert.match(script, /process\.env\.WAVE41_SUPPORT_PHONE/);
  assert.match(script, /process\.env\.WAVE41_SUPPORT_PASSWORD/);
  assert.match(script, /\/api\/v1\/auth\/me/);
  assert.match(script, /getByRole\('button', \{ name: 'ورود', exact: true \}\)\.click\(\)/);
  assert.match(script, /waitForURL\(\(url\) => url\.pathname === '\/support'/);
  assert.match(script, /1440, 900/);
  assert.match(script, /390, 844/);
  assert.match(script, /support-mobile-drawer-390x844\.png/);
  assert.doesNotMatch(script, /TEMP-Dev-Password|12345|addCookies|storageState\s*\(/);
  assert.match(runner, /hashPassword\(temporaryPassword\)/);
  assert.match(runner, /randomBytes\(32\)/);
  assert.match(runner, /childEnv\.WAVE41_SUPPORT_PHONE = fixture\.phone/);
  assert.match(runner, /childEnv\.WAVE41_SUPPORT_PASSWORD = temporaryPassword/);
  assert.doesNotMatch(runner, /childEnv = \{ \.\.\.process\.env/);
  assert.match(runner, /prisma\.authSession\.updateMany/);
  assert.doesNotMatch(runner, /console\.(log|error)\([^)]*(temporaryPhone|temporaryPassword)/);
});
