import { useState } from 'react';
import { createApiClient } from '../lib/api-client';
import { writeSession } from '../lib/session';

export function AuthForm({ mode = 'login' }) {
  const [phone, setPhone] = useState(''); const [password, setPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [code, setCode] = useState(''); const [loginOtp, setLoginOtp] = useState(false); const [step, setStep] = useState(mode === 'register' ? 'request' : 'password'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [passwordSetupToken, setPasswordSetupToken] = useState('');
  async function submit(event) { event.preventDefault(); setBusy(true); setMessage(''); const api = createApiClient(); try { if (mode === 'register' && step === 'request') { const result = await api.post('/auth/register/request-otp', { phone }); setMessage(result?.devCode ? `کد توسعه: ${result.devCode}` : 'کد تأیید ارسال شد.'); setStep('verify'); } else if (mode === 'register' && step === 'verify') { const result = await api.post('/auth/register/verify-otp', { phone, code }); setPasswordSetupToken(result.passwordSetupToken); setStep('set-password'); } else if (mode === 'register') { if (password !== confirm) throw new Error('رمزهای عبور یکسان نیستند.'); await api.post('/auth/register/set-password', { phone, password, passwordSetupToken }); const result = await api.post('/auth/login/password', { phone, password }); writeSession(result); globalThis.location.href = '/dashboard'; } else if (loginOtp && step === 'password') { const result = await api.post('/auth/login/request-otp', { phone }); setMessage(result?.devCode ? `کد توسعه: ${result.devCode}` : 'کد تأیید ارسال شد.'); setStep('verify'); } else if (loginOtp) { const result = await api.post('/auth/login/verify-otp', { phone, code }); writeSession(result); globalThis.location.href = '/dashboard'; } else { const result = await api.post('/auth/login/password', { phone, password }); writeSession(result); globalThis.location.href = '/dashboard'; } } catch (error) { setMessage(error.message); } finally { setBusy(false); } }
  return <form onSubmit={submit} aria-label={mode === 'register' ? 'ثبت‌نام' : 'ورود'}><label htmlFor="phone">شماره موبایل</label><input id="phone" value={phone} onChange={(e) => setPhone(e.target.value)} required autoComplete="tel" />{mode !== 'register' && <button type="button" onClick={() => { setLoginOtp(!loginOtp); setStep('password'); }}>ورود با {loginOtp ? 'رمز عبور' : 'کد یکبارمصرف'}</button>}{(mode !== 'register' && !loginOtp || mode === 'register' && step === 'set-password') && <label htmlFor="password">رمز عبور<input id="password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} required autoComplete="new-password" /></label>}{mode === 'register' && step === 'set-password' && <label htmlFor="confirm">تکرار رمز عبور<input id="confirm" type="password" value={confirm} onChange={(e) => setConfirm(e.target.value)} required /></label>}{((mode === 'register' && step === 'verify') || (mode !== 'register' && loginOtp && step === 'verify')) && <label htmlFor="code">کد تأیید<input id="code" value={code} onChange={(e) => setCode(e.target.value)} required inputMode="numeric" /></label>}<button disabled={busy} type="submit">{busy ? 'در حال ارسال…' : mode === 'register' ? (step === 'request' ? 'درخواست کد' : step === 'verify' ? 'تأیید کد' : 'تکمیل ثبت‌نام') : loginOtp && step === 'password' ? 'درخواست کد' : loginOtp ? 'تأیید و ورود' : 'ورود'}</button><p role="status">{message}</p></form>;
}
