import { useEffect, useState } from 'react';
import { createApiClient } from '../lib/api-client';
import { clearSession, readSession } from '../lib/session';

export function UserShell({ title, children }) {
  const [session, setSession] = useState(null);
  useEffect(() => { const current = readSession(); if (!current) { globalThis.location.href = '/login'; return; } setSession(current); }, []);
  async function logout() { try { await createApiClient({ getSession: () => session }).post('/auth/logout', session?.sessionId ? { sessionId: session.sessionId } : {}); } catch { /* local logout remains safe */ } clearSession(); globalThis.location.href = '/login'; }
  if (!session) return <main dir="rtl" lang="fa"><p>در حال بررسی نشست…</p></main>;
  return <main dir="rtl" lang="fa"><header className="app-header"><a className="brand" href="/dashboard"><span className="brand-mark" aria-hidden="true">ح</span><span><strong>حامی کارت</strong><small>سلامت، ساده و مطمئن</small></span></a><div className="header-account"><span className="account-label">حساب کاربری</span><button className="button button--ghost" type="button" onClick={logout}>خروج</button></div></header><div className="app-layout"><aside className="app-sidebar"><p className="nav-heading">فضای کاربری</p><nav aria-label="ناوبری کاربر"><a className="nav-link" href="/dashboard">داشبورد</a><a className="nav-link" href="/providers">پزشکان و مراکز</a><a className="nav-link" href="/redemptions">استفاده از مزیت</a><a className="nav-link" href="/plans">طرح‌ها</a><a className="nav-link" href="/purchases">خریدهای من</a><a className="nav-link" href="/memberships">عضویت‌ها</a><a className="nav-link" href="/wallet">کیف پول</a><p className="nav-heading nav-heading--spaced">همکاری و حساب</p><a className="nav-link" href="/providers/onboarding">درخواست همکاری پزشک</a><a className="nav-link" href="/providers/me">وضعیت همکاری پزشک</a><a className="nav-link" href="/providers/redemptions">تأیید استفاده</a><a className="nav-link" href="/rep-dashboard">داشبورد همکار</a><a className="nav-link" href="/attributed-customers">مشتریان منتسب</a><a className="nav-link" href="/commission-overview">خلاصه کمیسیون</a><a className="nav-link" href="/referrals">معرفی دوستان</a><a className="nav-link" href="/sales">همکار فروش</a><a className="nav-link" href="/profile">پروفایل</a><a className="nav-link" href="/addresses">آدرس‌ها</a></nav></aside><section className="app-content"><div className="content-title"><p className="page-eyebrow">حامی کارت</p><h1>{title}</h1></div>{children}</section></div></main>;
}
